### PR TITLE
Merge MonkeyC2

### PR DESCRIPTION
**Pull request by ehsanmasdar**

### CODE REVIEW

**Comment by smo-key** [comment]
@Oksisane This branch just needs a few final tests to verify that everything works. Leave the PR open, but we might need to add commits.

**Comment by smo-key** [comment]
@ethan-schaffer I could not find a working robot/phone pair yesterday, so all this needs is a robot test.

**Comment by Oksisane** [comment]
@homu r+

**Comment by smo-key** [comment]
See #26.

**Pull request closed without merging**
