### PR TITLE
Pull request Staging into MonkeyC

### PR DESCRIPTION
**Pull request by smo-key**

### CODE REVIEW

**Comment by smo-key** [comment]
@homu r+

**Comment by smo-key** [comment]
@homu retry

**Comment by smo-key** [comment]
@homu r+

**Comment by smo-key** [comment]
@homu r-

**Comment by smo-key** [comment]
@homu r+

**Comment by ehsanmasdar** [comment]
@homu r-

**Comment by Oksisane** [comment]
@smo-key Has this been tested???

**Comment by smo-key** [comment]
@Oksisane ?

**Comment by ehsanmasdar** [comment]
@smo-key Oh wait never mind :P

**Comment by smo-key** [comment]
This is a push FROM staging TO MonkeyC!

**Comment by ehsanmasdar** [comment]
@homu r+

**Comment by smo-key** [comment]
@homu isn't working.

**Comment by smo-key** [comment]
@homu r-

**Comment by smo-key** [comment]
@homu retry

**Comment by smo-key** [comment]
We should probably figure out what's wrong... because we really shouldn't be doing this into master when the time comes...

**Pull request merged**
