### PR TITLE
Merge continuous integration setup into staging

### PR DESCRIPTION
**Pull request by ehsanmasdar**
Uses Travis CI to provide builds.

### CODE REVIEW

**Comment by smo-key** [comment]
@Oksisane sweet! This looks great! Are you only running a build test? No unit tests yet?

**Comment by smo-key** [comment]
@Oksisane sweet! This looks great! Are you only running a build test? No unit tests yet?

**Comment by ehsanmasdar** [comment]
@smo-key Yep

**Comment by smo-key** [comment]
@Oksisane Add a few unit tests to the core library. This would greatly help later on...

**Pull request merged**
