### PR TITLE
MonkeyC 2.0 Merge v2

### PR DESCRIPTION
**Pull request by smo-key**
Let's fix issues.

### CODE REVIEW

**Comment by smo-key** [comment]
@Oksisane Why does Homu take so long to update checks? Does it require a new pull request to initiate?

**Comment by ehsanmasdar** [comment]
@smo-key The homu check ensures that only homu merges things. It essentially disables Github's merge pull request gui functionality

**Comment by smo-key** [comment]
@Oksisane Please review the videos I gave you and make @homu happy.  :smiley:

**Comment by ehsanmasdar** [comment]
@homu r+

**Pull request merged**
