### PR TITLE
Modern Robotics Gyroscope Support

### PR DESCRIPTION
**Pull request by ehsanmasdar**

### CODE REVIEW

**Comment by ehsanmasdar** [comment]
@smo-key Please test and sign off :)

**Comment by smo-key** [comment]
@Oksisane Code looks good - let's test tomorrow at lunch.

**Comment by ethan-schaffer** [comment]
@smo-key @oksisane you two are welcome to test on the 4290 bot.

On Thu, Oct 22, 2015 at 8:43 PM, Arthur Pachachura <notifications@github.com

**Comment by smo-key** [comment]
Thank you, @ethan-schaffer!

**Comment by ethan-schaffer** [comment]
No problem @smo-key!

On Thu, Oct 22, 2015 at 9:04 PM, Arthur Pachachura <notifications@github.com

**Comment by smo-key** [comment]
@Oksisane Tested. Please make a few changes:
- All methods should return a _signed_ integer. `signed = (unsigned >= 65526/2) ? 65525 - unsigned : unsigned;` should work, maybe some binary logic would be better
- Fix the stall when calling resetHeading() from `init()`

Also, the gyro is inaccurate when it moves really fast. Can you limit this somehow?

**Comment by smo-key** [comment]
@homu r-

**Pull request closed without merging**
