### PR TITLE
Merge FTC release for 9/18/15 into FTCLibrary

### PR DESCRIPTION
**Pull request by ehsanmasdar**

### CODE REVIEW

**Comment by smo-key** [comment]
@Oksisane What is this?

**Comment by ehsanmasdar** [comment]
@smo-key The new release of the ftc app

**Comment by smo-key** [comment]
@Oksisane Oh boy. This is going to mess up a lot of stuff, isn't it?

**Comment by ehsanmasdar** [comment]
@smo-key Nope, only thing that stopped working was TouchInternal, which does not matter anyways because the lib has support for touch sensors already

**Comment by smo-key** [comment]
Oh yeah, and to prevent failed builds due to destroying branches before Travis completes, all CI checks must complete on both `staging` and `master` even for us. Please leave this. :)

**Comment by ehsanmasdar** [comment]
@smo-key Yeah, I like that xD

**Comment by smo-key** [comment]
@Oksisane We should also implement the unspoken rule that the person that does NOT author the pull request must merge it. So that we don't lose any work in the future and can work things out.

**Pull request merged**
