### PR TITLE
Update to 10/06 release

### PR DESCRIPTION
**Pull request by ehsanmasdar**

### CODE REVIEW

**Comment by ethan-schaffer** [comment]
@Oksisane Was the weird connection fixed in this update, or is that on the agenda for tomorrow?

**Comment by Shwinn** [comment]
@ethan-schaffer If you are talking about the issue connecting the phone to the robot, I think I fixed it by changing the usb cable orientations (the USB cables are very bad quality).

**Comment by ethan-schaffer** [comment]
@shwinn lets hope so, we'll find out

**Comment by ehsanmasdar** [comment]
@ethan-schaffer @Shwinn The usb connection issue is a known problem with the Android system and widely reported by other teams. I don't think there's anything we are doing wrong, rather we probably just need to wait for a (hopefully soon) fix from FIRST.

**Comment by ethan-schaffer** [comment]
@okisane that stinks... oh well, I guess as long it's not just us!

**Comment by ehsanmasdar** [comment]
@homu r+

**Pull request merged**
